module.exports = [
  {
    id: 1,
    title: 'iPad Air 10.9 Wi-Fi 256GB New 2020 - Hàng Chính Hãng Apple',
    category: 'Apple',
    timer: 40,
    successAuction: 312,
    description: [
      'Thiết kế tinh tế, màu sắc thời thượng với độ mỏng 6.1mm',
      'Thiết kế của iPad Air 10.9 Wi-Fi New 2020 sẽ vuông vắn hơn so với những dòng iPad',
      'Màn hình có tần số quét 60Hz, tấm nền IPS LCD và kích thước 10.9 inch',
      'Chip A14 cho sức mạnh ấn tượng và bộ nhớ 128GB lưu trữ rộng rãi',
      'Hệ thống camera với cảm biến LiDAR hỗ trợ quay phim chất lượng 4K siêu nét',
    ],
    rate: 3.5,
    options: ['32GB', '64GB', '128GB', '256GB', '512GB'],
    priceTrade: 148000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/1.png',
      '/images/products/2.jpeg',
      '/images/products/3.jpeg',
      '/images/products/4.jpeg',
      '/images/products/5.jpeg',
    ],
  },
  {
    id: 2,
    title: 'Điện Thoại iPhone 12 Pro Max 128GB - Hàng Chính Hãng',
    category: 'iPhone 12',
    timer: 110,
    successAuction: 147,
    description: [
      'Màn hình Super Retina XDR 6.7 inch2',
      'Ceramic Shield, chất liệu kính bền chắc nhất từng có trên điện thoại thông minh',
      'Mạng 5G cho tốc độ tải xuống siêu nhanh, xem video và nghe nhạc trực tuyến chất lượng cao',
      'A14 Bionic, chip nhanh nhất từng có trên điện thoại thông minh',
      'Hệ thống camera chuyên nghiệp 12MP với camera Ultra Wide, Wide và Telephoto; phạm vi thu phóng quang học 5x; chế độ Ban Đêm, Deep Fusion, HDR thông minh thế hệ 3, Apple ProRAW, và khả năng quay video HDR Dolby Vision 4K',
      'LiDAR Scanner cải thiện trải nghiệm thực tế ảo tăng cường và chụp ảnh chân dung ở chế độ Ban Đêm',
      'iOS 14 với các tiện ích được thiết kế lại trên Màn Hình Chính, Thư Viện Ứng Dụng hoàn toàn mới, App Clips cùng nhiều tính năng khác',
    ],
    rate: 4,
    options: ['32GB', '64GB', '128GB', '256GB', '512GB'],
    priceTrade: 22000000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/6.jpeg',
      '/images/products/7.jpeg',
      '/images/products/8.jpeg',
      '/images/products/9.jpeg',
      '/images/products/10.jpeg',
    ],
  },

  {
    id: 3,
    title:
      'Tai Nghe Bluetooth Apple AirPods Pro True Wireless - MWP22 - Hàng Chính Hãng VN/A',
    category: 'AirPods',
    timer: 80,
    successAuction: 2270,
    description: [
      'Tính năng Chủ Động Khử Tiếng Ồn tạo ra âm thanh sống động',
      'Chế Độ Xuyên Âm giúp bạn nghe và tương tác với thế giới xung quanh',
      'Chế Độ Xuyên Âm giúp bạn nghe và tương tác với thế giới xung quanh',
      'EQ thích ứng sẽ tự động điều chỉnh nhạc theo kích thước tai của bạn',
      'Thiết lập dễ dàng cùng tính năng nhận biết khi đeo cho trải nghiệm tuyệt vời (2)',
    ],
    rate: 2.5,
    options: ['Màu trắng', 'Màu đen', 'Màu hồng'],
    priceTrade: 49500000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/11.jpeg',
      '/images/products/12.jpeg',
      '/images/products/13.jpeg',
      '/images/products/14.jpeg',
      '/images/products/15.jpeg',
    ],
  },

  {
    id: 4,
    title:
      'Apple iMac 21.5 2017 MHK03SA/A (Core i5 2.3GHz/ 8GB/ 256GB SSD/ FHD) - Hàng Chính Hãng',
    category: 'iMac',
    timer: 70,
    successAuction: 678,
    description: [
      'Bộ vi xử lý Intel Core i5 mạnh mẽ',
      'Màn hình Full HD sắc nét, màu sắc chính xác',
      'Tốc độ nhanh hơn với ổ cứng SSD',
      'Đầy đủ loạt kết nối hàng đầu',
    ],
    rate: 2.5,
    options: ['32GB', '64GB', '128GB', '256GB', '512GB'],
    priceTrade: 26000000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/16.jpeg',
      '/images/products/17.jpeg',
      '/images/products/18.jpeg',
      '/images/products/19.jpeg',
      '/images/products/20.png',
    ],
  },

  {
    id: 5,
    title:
      'Apple Macbook Pro 2020 M1 - 13 Inchs (Apple M1/ 8GB/ 256GB) - Hàng Chính Hãng',
    category: 'Macbook',
    timer: 110,
    successAuction: 1245,
    description: [
      'Chip M1 do Apple thiết kế tạo ra một cú nhảy vọt về hiệu năng máy học, CPU và GPU',
      'Làm được nhiều việc hơn với thời lượng pin lên đến 20 giờ, thời lượng pin lâu nhất trong các dòng máy tính Mac từ trước đến nay',
      'CPU 8 lõi cho hiệu năng nhanh hơn đến 2.8x, xử lý các luồng công việc nhanh hơn bao giờ hết',
      'GPU 8 lõi với tốc độ xử lý đồ họa nhanh gấp 5x cho các ứng dụng và game có đồ họa khủng',
      'Ổ lưu trữ SSD siêu nhanh khởi chạy ứng dụng và mở tập tin chỉ trong tích tắc',
      'Màn hình Retina với độ sáng 500 nit cho màu sắc sống động và chi tiết ấn tượng',
    ],
    rate: 3.5,
    options: ['128GB', '256GB', '512GB'],
    priceTrade: 31490000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/21.jpeg',
      '/images/products/22.jpeg',
      '/images/products/23.jpeg',
      '/images/products/24.jpeg',
      '/images/products/25.jpeg',
    ],
  },
  {
    id: 6,
    title:
      'Apple Mac Mini 2020 M1 (Apple M1/ 16GB/ 256GB) - Z12N000B8 - Hàng Chính Hãng',
    category: 'Mac mini',
    timer: 230,
    successAuction: 189,
    description: [
      'Bước nhảy vọt về hiệu năng',
      'CPU 8 nhân, xử lý mọi việc trong chớp mắt',
      'Sức mạnh đồ họa nhanh hơn tới 6 lần',
      'Giải phóng sức mạnh với 16 nhân Neural Engine',
      'Thiết kế nhỏ gọn',
      'Ổ cứng SSD siêu tốc',
      'Mở rộng kết nối',
    ],
    rate: 1.5,
    options: ['128GB', '256GB', '512GB'],
    priceTrade: 23499000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/26.jpeg',
      '/images/products/27.jpeg',
      '/images/products/28.png',
      '/images/products/29.jpeg',
      '/images/products/30.jpeg',
    ],
  },
  {
    id: 7,
    title:
      'Smart Tivi Samsung Màn Hình Cong UHD 4K 55 inch UA55TU8300KXXV - Miễn phí lắp đặt',
    category: 'Samsung',
    timer: 135,
    successAuction: 189,
    description: [
      'Loại màn hình: Màn hình cong',
      'Loại Tivi: Smart Tivi',
      'Sức mạnh đồ họa nhanh hơn tới 6 lần',
      'Kích thước màn hình: 55 inch',
      'Độ phân giải: Ultra HD 4K(3480 x 2160)',
      'Công nghệ hình ảnh:Mega Contrast, PurColor, Crystal Processor 4K , UHD Dimming, HDR10+, HLG',
      'Tổng công suất loa: 20W (2 loa mỗi loa 10 W)',
    ],
    rate: 2,
    options: ['27 inch', '55 inch', '48 inch'],
    priceTrade: 14590000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/31.jpeg',
      '/images/products/32.jpg',
      '/images/products/33.jpeg',
      '/images/products/34.png',
      '/images/products/35.jpeg',
    ],
  },
  {
    id: 8,
    title: 'Tay cầm chơi game ps4 pro - Bảo hành chính hãng 12 tháng',
    category: 'PS4',
    timer: 310,
    successAuction: 1245,
    description: [
      'Màu đen phiên bản mới nhất hiện nay',
      'Phiên bản tay cầm thế hệ mới có thêm dải đèn LED.',
      'Dùng trên các hệ máy : PS4, PC, Android Phone, Android TV.',
      'Hỗ trợ kết nối có dây (dùng cáp) hoặc không dây (bluetooth), khoảng cách kết nối không dây lên đến 10m',
      'Dễ dàng cài đặt và tinh chỉnh, phù hợp với máy PS4, Android, Win 7, Win 10 hoặc cao hơn',
    ],
    rate: 3.5,
    options: ['TAY BÓC MÁY', 'TAY FULLBOX', 'ĐỎ FULLBOX', 'XANH FULLBOX'],
    priceTrade: 1290000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/36.jpeg',
      '/images/products/37.jpeg',
      '/images/products/38.jpeg',
      '/images/products/39.jpeg',
      '/images/products/40.jpeg',
    ],
  },

  {
    id: 9,
    title:
      'Loa SoundBar 100 Âm Thanh Vòm Sống Động Phong Cách Rạp Phim, Fullbox, Chính Hãng GENIUS',
    category: 'SoundBar',
    timer: 100,
    successAuction: 312,
    description: [
      'Thiết kế siêu nhỏ gọn, tinh tế chắc chắn sẽ làm bạn hài lòng',
      'Kích thước (Dài x Rộng x Cao): 320mm x 65mm x 70 mm',
      'Trọng lượng: 476,5g',
      'Tổng công suất đầu ra: 6 W',
      'Đáp ứng điện trở: 3 Ω',
      'Độ nhạy: 600mv ± 100mv',
    ],
    rate: 3.5,
    options: ['Đen', 'Đỏ', 'Xanh', 'Vàng'],
    priceTrade: 239000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/41.jpeg',
      '/images/products/42.jpeg',
      '/images/products/43.jpeg',
      '/images/products/44.jpeg',
      '/images/products/44.jpeg',
    ],
  },

  {
    id: 10,
    title: 'Chuột KHÔNG DÂY Cao Cấp QUEEN-5 Chất Từng Centimet',
    category: 'Phụ kiện',
    timer: 200,
    successAuction: 2270,
    description: [
      'Kiểu kết nối: KẾT NỐI KHÔNG DÂY qua cổng USB',
      'Khoảng cách hoạt động lên tới 10m, tần số 2.4GHz',
      'Thiết kế tinh xảo từng góc cạnh, đẹp từng centimet (cầm là mê ngay)',
      'Được nghiên cứu bởi chuyên gia giúp người dùng sử dụng thoải mái, vừa tay và chống mỏi',
      'Độ phân giải quang học (độ nhạy) lên tới 2000 (dpi)',
      'Giao diện kết nối: cổng USB',
      'Dễ sử dụng, tương thích mọi loại máy tính, laptop',
    ],
    rate: 2.5,
    options: ['Màu trắng', 'Màu đen', 'Màu hồng'],
    priceTrade: 115000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/47.jpeg',
      '/images/products/49.jpeg',
      '/images/products/46.jpeg',
      '/images/products/48.jpeg',
      '/images/products/50.png',
    ],
  },
  {
    id: 11,
    title: 'Máy ảnh Canon 70D kèm lens kit 18-55 STM',
    category: 'Máy ảnh',
    timer: 240,
    successAuction: 236,
    description: [
      'Cảm biến CMOS độ phân giải 20.2 Megapixels',
      'Chip xử lý ảnh chuyên nghiệp Canon Digic V',
      'Hệ thống đo sáng thế hệ mới iFCL 63 vùng ảnh',
      'Hệ thống lấy nét tự động chính xác 19 điểm',
      'Độ nhạy sáng tới 25.600, chụp liên tục tới 10 hình/s',
      'Quay phim Full HD âm thanh Stereo, hỗ trợ Mic',
    ],
    rate: 4,
    options: ['Đen', 'Bạc', 'Đỏ', 'Vàng'],
    priceTrade: 9300000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/54.jpeg',
      '/images/products/51.jpeg',
      '/images/products/53.jpeg',
      '/images/products/55.jpeg',
      '/images/products/52.jpeg',
    ],
  },
  {
    id: 12,
    title:
      'Máy quay flycam DJI Mavic Air 2 hàng chính hãng bảo hành 12 tháng mới 100%',
    category: 'Flycam',
    timer: 30,
    successAuction: 678,
    description: [
      'Thời lượng bay: 34 phút',
      'Tốc độ tối đa: 43 mph/19 m/s (S-Mode), 26.8 mph/12 m/s (P-Mode), 11.2 mph/5 m/s (T-Mode)',
      'Cảm biến:1/2 inch, chụp ảnh 48 Mp',
      'Quay video 4K/60p',
      'ISO video: 100 - 6400',
      'Khẩu độ: F2.8.',
    ],
    rate: 2.5,
    options: ['Bản đơn basic', 'Bản Fly More Combo'],
    priceTrade: 23990000,
    priceCurrent: 1000,
    historyAuction: [],
    images: [
      '/images/products/56.jpeg',
      '/images/products/57.jpeg',
      '/images/products/58.jpeg',
      '/images/products/59.jpeg',
      '/images/products/60.jpeg',
    ],
  },
];
